### ISSUE TITLE
dsl_cpe_control_vrx-4.16.6.3

### ISSUE THREAD

**Issue by oam7575** [xdarklight/dsl_cpe_control_vrx#2]
As per subject line dsl_cpe_control_vrx version 4.16.6.3 is available as part of the Netgear DM200 GPL source package.

URL : http://www.downloads.netgear.com/files/GPL/DM200-GPL_V1.0.0.36.tar.bz2

wget http://www.downloads.netgear.com/files/GPL/DM200-GPL_V1.0.0.36.tar.bz2
extract:  tar jxf DM200-GPL_V1.0.0.36.tar.bz2
cd dl/
extract : tar zxf dsl_cpe_control_vrx-4.16.6.3.tar.gz

**Comment by xdarklight** [comment]
Hi,

I consider this repo as unmaintained because lantiq has released newer drivers and pushed them into LEDE:
* http://mirror2.openwrt.org/sources/dsl_cpe_control_vrx-4.16.6.3.tar.gz
* http://mirror2.openwrt.org/sources/dsl_cpe_control_vrx-4.17.18.6.tar.gz

I decided not to merge this due to the fact that there may be Netgear specific changes (as they are known for releasing highly flawed code with a wide attack surface).

Thanks for your contribution though!
